name: ci

on:
  workflow_dispatch: 
  push:
    branches:
    - main
    paths-ignore:
    - '*.md'
    - '.gitignore'
    - '.vscode/*'
    - '.devcontainer/*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'
        dotnet-quality: 'preview'
    - name: workload
      run: |
        dotnet workload restore
    - name: test
      run: |
        dotnet test
    - name: registerSuccess
      run: |
        echo ${{ github.sha }} > commitHash.txt
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: lastSuccessfulCommit
        path: commitHash.txt
        if-no-files-found: error
        overwrite: true
